# Generated by Django 3.0.1 on 2020-01-28 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bookcrossing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='lib_id',
            new_name='lib',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='library',
            old_name='user_id',
            new_name='user',
        ),
    ]
