# Generated by Django 3.0.1 on 2020-01-29 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bookcrossing', '0002_auto_20200128_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Bookcrossing.User'),
        ),
    ]
